repos:
  - repo: local
    hooks:
      - id: ruff
        name: Ruff
        entry: uv run ruff check
        language: system
        types: [python]
      - id: mypy
        name: Mypy
        entry: uv run mypy
        args: [--config-file=./pyproject.toml]
        language: system
        files: 'src\/.*\.py'
