services:
  service:
    container_name: "service"
    hostname: "service"
    build:
      dockerfile: "./Dockerfile"
    ports:
      - "80:80"
    depends_on:
      - "postgresql"
    restart: "always"
  
  postgresql:
    hostname: "postgresql"
    container_name: "postgresql"
    image: "postgres:latest"
    shm_size: 128mb
    env_file:
      - "./.env"
    volumes:
      - "./database/:/var/lib/postgresql/data/"
    ports:
      - "${DB_PORT}:${DB_PORT}"
    restart: "always"
  
  redis:
    hostname: "redis"
    container_name: "redis"
    image: "redis:latest"
    command: redis-server --requirepass ${REDIS_PASSWORD}
    env_file:
      - "./.env"
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
    volumes:
      - "./redisdata/:/data/"
    restart: "always"
