"""empty message.

Revision ID: d2ec60b816de
Revises:
Create Date: 2025-03-03 21:20:57.853579

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d2ec60b816de"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table("posts",
    sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
    sa.Column("title", sa.String(), nullable=False),
    sa.PrimaryKeyConstraint("id"),
    )
    op.create_table("users",
    sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
    sa.Column("first_name", sa.String(), nullable=False),
    sa.Column("last_name", sa.String(), nullable=False),
    sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("users")
    op.drop_table("posts")
    # ### end Alembic commands ###
