"""empty message.

Revision ID: df0bbd74e781
Revises: a2e693bb7db0
Create Date: 2025-03-04 00:15:36.454912

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "df0bbd74e781"
down_revision: str | None = "a2e693bb7db0"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("images", sa.Column("post_id", sa.Integer(), nullable=False))
    op.create_foreign_key(None, "images", "posts", ["post_id"], ["id"])
    op.add_column("posts", sa.Column("user_id", sa.Integer(), nullable=False))
    op.create_foreign_key(None, "posts", "users", ["user_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "posts", type_="foreignkey")
    op.drop_column("posts", "user_id")
    op.drop_constraint(None, "images", type_="foreignkey")
    op.drop_column("images", "post_id")
    # ### end Alembic commands ###
