"""empty message.

Revision ID: fd5535258428
Revises: df0bbd74e781
Create Date: 2025-03-04 11:39:48.187304

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "fd5535258428"
down_revision: str | None = "df0bbd74e781"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("login", sa.String(), nullable=False))
    op.add_column("users", sa.Column("password", sa.String(), nullable=False))
    op.add_column("users", sa.Column("is_admin", sa.Boolean(), nullable=False))
    op.create_unique_constraint(None, "users", ["login"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "users", type_="unique")
    op.drop_column("users", "is_admin")
    op.drop_column("users", "password")
    op.drop_column("users", "login")
    # ### end Alembic commands ###
