name: Lint & type check

on:
  push:
  pull_request:

jobs:
  lint_and_type_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v5
      - run: uv sync
      - run: uv run ruff check
      - run: uv run mypy ./src/
